# Site settings
title: "akanksha shrivastava"
description: ""
baseurl: ""
url: "http://akankshashriv.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /index
  - title: "professional"
    url: /prof
  - title: "resume"
    url: /resume.pdf
  - title: "github"
    url: "http://github.com/akankshashriv"
  
