# Site settings
title: ""
description: ""
baseurl: ""
url: "http://akankshashriv.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "home"
    url: /index
  - title: "about"
    url: /about
  - title: "professional"
    url: /prof
  
